# ==========================================
# RocketMQ Broker
# ==========================================

# Broker 集群名称
brokerClusterName=DefaultCluster

# Broker 名称
brokerName=broker-a

# 0 = Master
brokerId=0


# ==========================================
# Network
# ==========================================

# Broker Remoting 端口
listenPort=10911

# NameServer
namesrvAddr=rmqnamesrv:9876

# Broker 对外公布的 IP
#
# 注意：
# 新服务器部署时需要修改成服务器公网 IP
#
brokerIP1=152.136.21.173


# ==========================================
# Topic
# ==========================================

# 开发/测试环境允许自动创建 Topic
autoCreateTopicEnable=true


# ==========================================
# Flush
# ==========================================

flushDiskType=ASYNC_FLUSH


# ==========================================
# Storage
# ==========================================

storePathRootDir=/home/rocketmq/store

storePathCommitLog=/home/rocketmq/store/commitlog

storePathConsumeQueue=/home/rocketmq/store/consumequeue

storePathIndex=/home/rocketmq/store/index

storePathCheckpoint=/home/rocketmq/store/checkpoint

storePathAbort=/home/rocketmq/store/abort


# ==========================================
# Message retention
# ==========================================

# 每天凌晨 4 点删除过期文件
deleteWhen=04

# 文件保留 48 小时
fileReservedTime=48